package com.sszg.atlassianproject.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Component;

import javax.validation.constraints.NotNull;
import java.util.List;
import java.util.Set;

// TODO: Explain why all these annotations are needed
@DynamoDBTable(tableName = "accounts")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Component
public class Account {
    // Each contact will have its own unique Id
    @DynamoDBHashKey(attributeName = "uid")
    @DynamoDBAutoGeneratedKey
    private String uid;
    @DynamoDBAttribute
    @NotNull
    private String companyName;
    @DynamoDBAttribute
    @NotNull
    private String addressLine1;
    @DynamoDBAttribute
    @NotNull
    private String addressLine2;
    @DynamoDBAttribute
    @NotNull
    private String city;
    @DynamoDBAttribute
    @NotNull
    private String state;
    @DynamoDBAttribute
    @NotNull
    private String postalCode;
    @DynamoDBAttribute
    @NotNull
    private String country;
    // TODO: Make contactIds default to empty list not null
    @DynamoDBAttribute
    @NotNull
    private Set<String> contactIds;
}
